"""empty message

Revision ID: 2a5391ede105
Revises: e0188d42f404
Create Date: 2020-03-03 16:04:26.531123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a5391ede105'
down_revision = 'e0188d42f404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###
