"""empty message

Revision ID: 38a640b387b8
Revises: 7af2f381629a
Create Date: 2020-03-02 17:48:46.920918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a640b387b8'
down_revision = '7af2f381629a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('uri', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'uri')
    # ### end Alembic commands ###
